
const translations = {
  en: {
    nav_about:"About", nav_work:"Our Work", nav_resources:"Resources", nav_course:"Digital Course", nav_emergency:"Emergency Basics", nav_partners:"For Organizations", nav_get_involved:"Get Involved",
    hero_eyebrow:"COMMUNITY WATER SAFETY EDUCATION", hero_title1:"Know the water.", hero_title2:"Stay safe.", hero_text:"WaterSafe makes reliable, practical water-safety education more accessible to communities through workshops, digital resources, and community partnerships.", hero_btn1:"Explore our work", hero_btn2:"Partner with us",
    approach_label:"OUR APPROACH", approach_title:"Knowledge before the water.", approach_text:"We focus on helping people recognize risks, understand their surroundings, and make informed decisions around water.", stat_workshops:"min workshops", stat_model:"community model", stat_free:"Free", stat_education:"pilot education",
    mission_eyebrow:"OUR MISSION", mission_title:"Making water-safety knowledge accessible to everyone.", mission_text:"WaterSafe is dedicated to making reliable, accessible water-safety education available to communities everywhere. Through community education, digital resources, and partnerships, we aim to equip people with the knowledge and confidence to recognize water-related risks, make safer decisions, and connect with opportunities to develop essential water-safety skills.",
    value_safety_title:"Safety", value_safety_text:"We turn essential water-safety knowledge into practical guidance people can understand, remember, and apply.", value_access_title:"Accessibility", value_access_text:"Education should be understandable and reachable regardless of someone's previous swimming experience or background.", value_community_title:"Community", value_community_text:"We work alongside organizations and communities rather than building a separate system from the ground up.",
    work_eyebrow:"OUR WORK", work_title:"Education designed to travel.", work_intro:"We build reusable resources that can reach people where they already learn, gather, and connect.", work1_title:"Community Workshops", work1_text:"A free, approximately 30-minute introduction to essential water safety, designed to be hosted by community organizations.", work1_li1:"Common water hazards", work1_li2:"Supervision and safer behavior", work1_li3:"Life jackets and PFD awareness", work1_li4:"When and how to seek help", work1_li5:"Next steps and local resources", work2_title:"Digital Library", work2_text:"Short videos, visual guides, and concise resources that make water-safety concepts easier to learn and share.", work3_title:"Resource Map", work3_text:"A practical way to connect people with existing swimming lessons, aquatic facilities, and water-safety programs.", work4_title:"Workshop Kit", work4_text:"A reusable package for partner organizations: presentation, facilitator guide, participant handout, resources, and evaluation tools.",
    workshop_eyebrow:"THE 30-MINUTE WORKSHOP", workshop_title:"Simple enough to access. Serious enough to matter.", workshop_intro:"The WaterSafe workshop is an educational introduction to water safety—not a replacement for professional swimming, lifeguarding, rescue, or first-aid training.", workshop_request:"Request a workshop →", timeline1_title:"Understand the risks", timeline1_text:"Recognize hazards in pools, lakes, rivers, and other environments.", timeline2_title:"Make safer decisions", timeline2_text:"Explore supervision, safer behavior, PFD awareness, and common misconceptions.", timeline3_title:"Know what to do next", timeline3_text:"Learn where to find reliable information and opportunities for further skills development.",
    course_eyebrow:"DIGITAL COURSE", course_title:"Learn at your own depth.", course_intro:"A self-paced collection of WaterSafe lessons designed to help you build water-safety knowledge whenever and wherever you learn best.", course_video_title:"Video lessons coming soon", course_video_text:"Your course videos will appear here.", course_lesson1:"Understanding water hazards", course_lesson2:"Safer decisions around water", course_lesson3:"Emergency basics",
    resources_eyebrow:"WATER SAFETY", resources_title:"Learn before you need it.", resources_intro:"Our resources are designed to be clear, practical, and easy to share.", res1_title:"Know the Environment", res1_text:"Water can change quickly. Learn to identify conditions and hazards before entering.", res2_title:"Know Your Limits", res2_text:"Swimming ability is only one part of water safety. Preparation and awareness matter too.", res3_title:"Know Where to Learn", res3_text:"Find reliable pathways to swimming instruction and other water-safety education.", coming_soon:"Coming soon →",
    emergency_eyebrow:"EMERGENCY BASICS", emergency_title:"Reach. Throw. Don't go.", emergency_intro:"If someone is in trouble in the water, protect yourself first. Do not enter the water unless you are trained to perform a rescue.", call_911:"Call 911 for emergency help.", em1_title:"The Golden Rule", em1_text:"Never put yourself in danger to rescue someone else. Stay on land and use a safe rescue method.", em2_title:"Reach with a pole", em2_text:"From a safe position on shore, extend a pole or another suitable reaching aid toward the person so they can grab it.", em3_title:"Throw a buoyancy aid", em3_text:"Throw a buoyancy aid, such as a life ring, toward the person. Do not throw yourself into the water.", em4_title:"Never enter unless trained", em4_text:"Water rescues can be dangerous. Never enter the water to perform a rescue unless you are appropriately trained.",
    partners_eyebrow:"FOR ORGANIZATIONS", partners_title:"Bring WaterSafe to your community.", partners_intro:"We partner with community organizations that want to offer an accessible introduction to water safety. There is no cost to the organization or participants during our pilot.", partner_host:"Host", partner_host_text:"A free ~30-minute workshop at a time that fits your programming.", partner_share:"Share", partner_share_text:"Make WaterSafe's digital resources available to your community.", partner_shape:"Shape", partner_shape_text:"Help us understand community needs and improve the program.", partner_btn:"Discuss a partnership",
    contact_eyebrow:"GET INVOLVED", contact_title:"Let's make water-safety education easier to access.", contact_intro:"Interested in hosting a workshop, sharing resources, volunteering, or collaborating with WaterSafe?", form_name_label:"Name", form_name_placeholder:"Your name", form_org_label:"Organization", form_org_placeholder:"Organization (optional)", form_email_label:"Email", form_email_placeholder:"you@example.com", form_message_label:"How can we work together?", form_message_placeholder:"Tell us a little about your idea...", form_submit:"Send inquiry", form_note:"This demo form is ready to connect to your preferred email/form service.", footer_tagline:"Know the water. Stay safe.", footer_text:"Student-led water-safety education."
  },
  fr: {
    nav_about:"À propos", nav_work:"Nos actions", nav_resources:"Ressources", nav_course:"Cours numérique", nav_emergency:"Notions d'urgence", nav_partners:"Pour les organismes", nav_get_involved:"Participer",
    hero_eyebrow:"ÉDUCATION COMMUNAUTAIRE À LA SÉCURITÉ AQUATIQUE", hero_title1:"Comprendre l'eau.", hero_title2:"Rester en sécurité.", hero_text:"WaterSafe rend l'éducation fiable et pratique à la sécurité aquatique plus accessible aux communautés grâce à des ateliers, des ressources numériques et des partenariats communautaires.", hero_btn1:"Découvrir nos actions", hero_btn2:"Devenir partenaire",
    approach_label:"NOTRE APPROCHE", approach_title:"Le savoir avant d'entrer dans l'eau.", approach_text:"Nous aidons les personnes à reconnaître les risques, à comprendre leur environnement et à prendre des décisions éclairées autour de l'eau.", stat_workshops:"min d'atelier", stat_model:"modèle communautaire", stat_free:"Gratuit", stat_education:"projet pilote",
    mission_eyebrow:"NOTRE MISSION", mission_title:"Rendre les connaissances en sécurité aquatique accessibles à tous.", mission_text:"WaterSafe a pour mission de rendre l'éducation fiable et accessible à la sécurité aquatique disponible dans les communautés partout. Grâce à l'éducation communautaire, aux ressources numériques et aux partenariats, nous voulons donner aux personnes les connaissances et la confiance nécessaires pour reconnaître les risques liés à l'eau, prendre des décisions plus sûres et trouver des occasions de développer des compétences essentielles en sécurité aquatique.",
    value_safety_title:"Sécurité", value_safety_text:"Nous transformons les connaissances essentielles en sécurité aquatique en conseils pratiques que chacun peut comprendre, retenir et appliquer.", value_access_title:"Accessibilité", value_access_text:"L'éducation doit être compréhensible et accessible, quelle que soit l'expérience antérieure de natation ou l'origine de la personne.", value_community_title:"Communauté", value_community_text:"Nous travaillons avec les organismes et les communautés plutôt que de créer un système séparé à partir de zéro.",
    work_eyebrow:"NOS ACTIONS", work_title:"Une éducation conçue pour se transmettre.", work_intro:"Nous créons des ressources réutilisables qui peuvent rejoindre les personnes là où elles apprennent, se rassemblent et échangent.", work1_title:"Ateliers communautaires", work1_text:"Une introduction gratuite d'environ 30 minutes à la sécurité aquatique essentielle, conçue pour être offerte par des organismes communautaires.", work1_li1:"Risques aquatiques courants", work1_li2:"Surveillance et comportements plus sûrs", work1_li3:"Gilets de sauvetage et dispositifs de flottaison", work1_li4:"Quand et comment demander de l'aide", work1_li5:"Prochaines étapes et ressources locales", work2_title:"Bibliothèque numérique", work2_text:"De courtes vidéos, des guides visuels et des ressources concises pour faciliter l'apprentissage et le partage des notions de sécurité aquatique.", work3_title:"Carte des ressources", work3_text:"Un moyen pratique de mettre les personnes en relation avec les cours de natation, installations aquatiques et programmes de sécurité aquatique existants.", work4_title:"Trousse d'atelier", work4_text:"Une trousse réutilisable pour les organismes partenaires : présentation, guide d'animation, fiche pour les participants, ressources et outils d'évaluation.",
    workshop_eyebrow:"L'ATELIER DE 30 MINUTES", workshop_title:"Accessible. Sérieux. Utile.", workshop_intro:"L'atelier WaterSafe est une introduction éducative à la sécurité aquatique — il ne remplace pas une formation professionnelle en natation, en sauvetage, en intervention ou en premiers soins.", workshop_request:"Demander un atelier →", timeline1_title:"Comprendre les risques", timeline1_text:"Reconnaître les dangers dans les piscines, les lacs, les rivières et autres environnements.", timeline2_title:"Prendre de meilleures décisions", timeline2_text:"Explorer la surveillance, les comportements plus sûrs, les dispositifs de flottaison et les idées reçues.", timeline3_title:"Savoir quoi faire ensuite", timeline3_text:"Savoir où trouver des informations fiables et des possibilités de développer ses compétences.",
    course_eyebrow:"COURS NUMÉRIQUE", course_title:"Apprenez à votre rythme.", course_intro:"Une collection de leçons WaterSafe à suivre à votre rythme pour développer vos connaissances en sécurité aquatique, quand et où vous apprenez le mieux.", course_video_title:"Vidéos à venir", course_video_text:"Vos vidéos de cours apparaîtront ici.", course_lesson1:"Comprendre les dangers de l'eau", course_lesson2:"Prendre de meilleures décisions autour de l'eau", course_lesson3:"Notions d'urgence",
    resources_eyebrow:"SÉCURITÉ AQUATIQUE", resources_title:"Apprendre avant d'en avoir besoin.", resources_intro:"Nos ressources sont conçues pour être claires, pratiques et faciles à partager.", res1_title:"Connaître son environnement", res1_text:"Les conditions peuvent changer rapidement. Apprenez à repérer les conditions et les dangers avant d'entrer dans l'eau.", res2_title:"Connaître ses limites", res2_text:"La capacité à nager n'est qu'un aspect de la sécurité aquatique. La préparation et la vigilance comptent aussi.", res3_title:"Savoir où apprendre", res3_text:"Trouvez des moyens fiables d'accéder à des cours de natation et à d'autres formations en sécurité aquatique.", coming_soon:"Bientôt disponible →",
    emergency_eyebrow:"NOTIONS D'URGENCE", emergency_title:"Tendez. Lancez. N'entrez pas.", emergency_intro:"Si une personne est en difficulté dans l'eau, protégez-vous d'abord. N'entrez pas dans l'eau pour effectuer un sauvetage, sauf si vous êtes formé pour le faire.", call_911:"Appelez le 911 en cas d'urgence.", em1_title:"La règle d'or", em1_text:"Ne vous mettez jamais en danger pour secourir quelqu'un. Restez sur la terre ferme et utilisez une méthode de sauvetage sécuritaire.", em2_title:"Tendre une perche", em2_text:"Depuis une position sûre sur la rive, tendez une perche ou un autre objet adapté pour que la personne puisse l'attraper.", em3_title:"Lancer un dispositif flottant", em3_text:"Lancez un dispositif de flottaison, comme une bouée, vers la personne. Ne vous jetez pas dans l'eau.", em4_title:"N'entrez jamais sans formation", em4_text:"Les sauvetages aquatiques peuvent être dangereux. N'entrez jamais dans l'eau pour effectuer un sauvetage si vous n'avez pas la formation appropriée.",
    partners_eyebrow:"POUR LES ORGANISMES", partners_title:"Amenez WaterSafe dans votre communauté.", partners_intro:"Nous travaillons avec des organismes communautaires qui souhaitent offrir une introduction accessible à la sécurité aquatique. Pendant notre projet pilote, il n'y a aucun coût pour l'organisme ni pour les participants.", partner_host:"Accueillir", partner_host_text:"Un atelier gratuit d'environ 30 minutes, à un moment qui convient à votre programmation.", partner_share:"Partager", partner_share_text:"Rendre les ressources numériques de WaterSafe accessibles à votre communauté.", partner_shape:"Contribuer", partner_shape_text:"Nous aider à comprendre les besoins de la communauté et à améliorer le programme.", partner_btn:"Discuter d'un partenariat",
    contact_eyebrow:"PARTICIPER", contact_title:"Rendons l'éducation à la sécurité aquatique plus accessible.", contact_intro:"Vous souhaitez accueillir un atelier, partager des ressources, faire du bénévolat ou collaborer avec WaterSafe ?", form_name_label:"Nom", form_name_placeholder:"Votre nom", form_org_label:"Organisme", form_org_placeholder:"Organisme (facultatif)", form_email_label:"Courriel", form_email_placeholder:"vous@exemple.com", form_message_label:"Comment pouvons-nous collaborer ?", form_message_placeholder:"Parlez-nous un peu de votre idée...", form_submit:"Envoyer la demande", form_note:"Ce formulaire de démonstration peut être relié à votre service de courriel ou de formulaires préféré.", footer_tagline:"Comprendre l'eau. Rester en sécurité.", footer_text:"Éducation étudiante à la sécurité aquatique."
  },
  hi: {
    nav_about:"हमारे बारे में", nav_work:"हमारा काम", nav_resources:"संसाधन", nav_course:"डिजिटल कोर्स", nav_emergency:"आपातकालीन मूल बातें", nav_partners:"संस्थाओं के लिए", nav_get_involved:"जुड़ें",
    hero_eyebrow:"सामुदायिक जल-सुरक्षा शिक्षा", hero_title1:"पानी को समझें।", hero_title2:"सुरक्षित रहें।", hero_text:"WaterSafe कार्यशालाओं, डिजिटल संसाधनों और सामुदायिक साझेदारियों के माध्यम से विश्वसनीय और व्यावहारिक जल-सुरक्षा शिक्षा को समुदायों के लिए अधिक सुलभ बनाता है।", hero_btn1:"हमारा काम देखें", hero_btn2:"हमारे साथ साझेदारी करें",
    approach_label:"हमारा दृष्टिकोण", approach_title:"पानी में उतरने से पहले ज्ञान।", approach_text:"हम लोगों को जोखिम पहचानने, अपने आसपास के वातावरण को समझने और पानी के आसपास सोच-समझकर निर्णय लेने में मदद करते हैं।", stat_workshops:"मिनट की कार्यशालाएँ", stat_model:"सामुदायिक मॉडल", stat_free:"निःशुल्क", stat_education:"पायलट शिक्षा",
    mission_eyebrow:"हमारा मिशन", mission_title:"जल-सुरक्षा का ज्ञान सभी के लिए सुलभ बनाना।", mission_text:"WaterSafe का उद्देश्य विश्वसनीय और सुलभ जल-सुरक्षा शिक्षा को हर समुदाय तक पहुँचाना है। सामुदायिक शिक्षा, डिजिटल संसाधनों और साझेदारियों के माध्यम से हम लोगों को पानी से जुड़े जोखिमों को पहचानने, सुरक्षित निर्णय लेने और आवश्यक जल-सुरक्षा कौशल विकसित करने के अवसर खोजने के लिए ज्ञान और आत्मविश्वास देना चाहते हैं।",
    value_safety_title:"सुरक्षा", value_safety_text:"हम आवश्यक जल-सुरक्षा ज्ञान को ऐसे व्यावहारिक मार्गदर्शन में बदलते हैं जिसे लोग समझ, याद और लागू कर सकें।", value_access_title:"सुलभता", value_access_text:"शिक्षा ऐसी होनी चाहिए जिसे हर व्यक्ति अपनी तैराकी के अनुभव या पृष्ठभूमि की परवाह किए बिना समझ और प्राप्त कर सके।", value_community_title:"समुदाय", value_community_text:"हम अलग व्यवस्था शुरू करने के बजाय संगठनों और समुदायों के साथ मिलकर काम करते हैं।",
    work_eyebrow:"हमारा काम", work_title:"ऐसी शिक्षा जो आगे साझा की जा सके।", work_intro:"हम ऐसे पुनः उपयोग योग्य संसाधन बनाते हैं जो लोगों तक वहीं पहुँच सकें जहाँ वे सीखते, मिलते और जुड़ते हैं।", work1_title:"सामुदायिक कार्यशालाएँ", work1_text:"आवश्यक जल-सुरक्षा का लगभग 30 मिनट का निःशुल्क परिचय, जिसे सामुदायिक संगठन आयोजित कर सकते हैं।", work1_li1:"सामान्य जल-जोखिम", work1_li2:"निगरानी और सुरक्षित व्यवहार", work1_li3:"लाइफ जैकेट और व्यक्तिगत तैरने वाले उपकरण", work1_li4:"कब और कैसे मदद माँगें", work1_li5:"अगले कदम और स्थानीय संसाधन", work2_title:"डिजिटल लाइब्रेरी", work2_text:"छोटी वीडियो, दृश्य मार्गदर्शिकाएँ और संक्षिप्त संसाधन जो जल-सुरक्षा सीखना और साझा करना आसान बनाते हैं।", work3_title:"संसाधन मानचित्र", work3_text:"लोगों को मौजूदा तैराकी कक्षाओं, जलीय सुविधाओं और जल-सुरक्षा कार्यक्रमों से जोड़ने का व्यावहारिक तरीका।", work4_title:"वर्कशॉप किट", work4_text:"साझेदार संगठनों के लिए पुनः उपयोग योग्य पैकेज: प्रस्तुति, संचालक मार्गदर्शिका, प्रतिभागी सामग्री, संसाधन और मूल्यांकन उपकरण।",
    workshop_eyebrow:"30 मिनट की कार्यशाला", workshop_title:"आसानी से उपलब्ध। गंभीरता से उपयोगी।", workshop_intro:"WaterSafe कार्यशाला जल-सुरक्षा का एक शैक्षिक परिचय है—यह पेशेवर तैराकी, लाइफगार्ड, बचाव या प्राथमिक उपचार प्रशिक्षण का विकल्प नहीं है।", workshop_request:"कार्यशाला का अनुरोध करें →", timeline1_title:"जोखिम समझें", timeline1_text:"पूल, झील, नदी और अन्य वातावरणों में खतरों को पहचानें।", timeline2_title:"सुरक्षित निर्णय लें", timeline2_text:"निगरानी, सुरक्षित व्यवहार, तैरने वाले उपकरण और आम गलत धारणाओं को समझें।", timeline3_title:"आगे क्या करना है जानें", timeline3_text:"विश्वसनीय जानकारी और आगे कौशल विकसित करने के अवसर कहाँ मिलते हैं, यह जानें।",
    course_eyebrow:"डिजिटल कोर्स", course_title:"अपनी गति से सीखें।", course_intro:"WaterSafe के स्व-गति वाले पाठ, जिनसे आप जब और जहाँ सुविधाजनक हो, जल-सुरक्षा का ज्ञान विकसित कर सकते हैं।", course_video_title:"वीडियो पाठ जल्द आ रहे हैं", course_video_text:"आपके कोर्स के वीडियो यहाँ दिखाई देंगे।", course_lesson1:"जल-जोखिम को समझना", course_lesson2:"पानी के आसपास सुरक्षित निर्णय", course_lesson3:"आपातकालीन मूल बातें",
    resources_eyebrow:"जल-सुरक्षा", resources_title:"ज़रूरत पड़ने से पहले सीखें।", resources_intro:"हमारे संसाधन स्पष्ट, व्यावहारिक और आसानी से साझा किए जा सकने के लिए बनाए गए हैं।", res1_title:"अपने वातावरण को जानें", res1_text:"पानी की स्थिति जल्दी बदल सकती है। प्रवेश करने से पहले परिस्थितियों और खतरों को पहचानना सीखें।", res2_title:"अपनी सीमाएँ जानें", res2_text:"तैरने की क्षमता जल-सुरक्षा का केवल एक हिस्सा है। तैयारी और जागरूकता भी महत्वपूर्ण हैं।", res3_title:"कहाँ सीखना है जानें", res3_text:"तैराकी शिक्षा और अन्य जल-सुरक्षा प्रशिक्षण तक पहुँचने के विश्वसनीय रास्ते खोजें।", coming_soon:"जल्द आ रहा है →",
    emergency_eyebrow:"आपातकालीन मूल बातें", emergency_title:"पहुंचें। फेंकें। अंदर न जाएँ।", emergency_intro:"अगर कोई व्यक्ति पानी में मुसीबत में है, तो पहले अपनी सुरक्षा करें। जब तक आप बचाव के लिए प्रशिक्षित न हों, पानी में प्रवेश न करें।", call_911:"आपातकाल में 911 पर कॉल करें।", em1_title:"सुनहरा नियम", em1_text:"किसी और को बचाने के लिए खुद को कभी खतरे में न डालें। किनारे पर रहें और सुरक्षित बचाव विधि का उपयोग करें।", em2_title:"डंडे से पहुँचें", em2_text:"किनारे पर सुरक्षित स्थान से डंडा या कोई उपयुक्त पहुँचने वाला उपकरण व्यक्ति की ओर बढ़ाएँ ताकि वह उसे पकड़ सके।", em3_title:"तैरने वाला उपकरण फेंकें", em3_text:"लाइफ रिंग जैसे तैरने वाले उपकरण को व्यक्ति की ओर फेंकें। खुद पानी में न कूदें।", em4_title:"प्रशिक्षित न हों तो अंदर न जाएँ", em4_text:"जल-बचाव खतरनाक हो सकता है। उचित प्रशिक्षण के बिना बचाव करने के लिए कभी पानी में प्रवेश न करें।",
    partners_eyebrow:"संगठनों के लिए", partners_title:"WaterSafe को अपने समुदाय तक पहुँचाएँ।", partners_intro:"हम उन सामुदायिक संगठनों के साथ साझेदारी करते हैं जो जल-सुरक्षा का सुलभ परिचय देना चाहते हैं। हमारे पायलट के दौरान संगठन या प्रतिभागियों के लिए कोई शुल्क नहीं है।", partner_host:"आयोजित करें", partner_host_text:"अपने कार्यक्रम के अनुसार लगभग 30 मिनट की निःशुल्क कार्यशाला आयोजित करें।", partner_share:"साझा करें", partner_share_text:"WaterSafe के डिजिटल संसाधनों को अपने समुदाय के लिए उपलब्ध कराएँ।", partner_shape:"सहयोग दें", partner_shape_text:"हमें समुदाय की जरूरतें समझने और कार्यक्रम बेहतर बनाने में मदद करें।", partner_btn:"साझेदारी पर चर्चा करें",
    contact_eyebrow:"जुड़ें", contact_title:"जल-सुरक्षा शिक्षा को अधिक सुलभ बनाएं।", contact_intro:"क्या आप कार्यशाला आयोजित करना, संसाधन साझा करना, स्वयंसेवा करना या WaterSafe के साथ सहयोग करना चाहते हैं?", form_name_label:"नाम", form_name_placeholder:"आपका नाम", form_org_label:"संगठन", form_org_placeholder:"संगठन (वैकल्पिक)", form_email_label:"ईमेल", form_email_placeholder:"you@example.com", form_message_label:"हम साथ कैसे काम कर सकते हैं?", form_message_placeholder:"अपने विचार के बारे में थोड़ा बताएं...", form_submit:"अनुरोध भेजें", form_note:"यह डेमो फ़ॉर्म आपके पसंदीदा ईमेल या फ़ॉर्म सेवा से जोड़ा जा सकता है।", footer_tagline:"पानी को समझें। सुरक्षित रहें।", footer_text:"छात्र-नेतृत्व वाली जल-सुरक्षा शिक्षा।"
  },
  ar: {
    nav_about:"من نحن", nav_work:"عملنا", nav_resources:"الموارد", nav_course:"الدورة الرقمية", nav_emergency:"أساسيات الطوارئ", nav_partners:"للمنظمات", nav_get_involved:"شارك",
    hero_eyebrow:"التثقيف المجتمعي حول سلامة المياه", hero_title1:"افهم الماء.", hero_title2:"ابقَ آمناً.", hero_text:"تجعل WaterSafe التثقيف الموثوق والعملي حول سلامة المياه أكثر إتاحة للمجتمعات من خلال ورش العمل والموارد الرقمية والشراكات المجتمعية.", hero_btn1:"استكشف عملنا", hero_btn2:"شاركنا كشريك",
    approach_label:"نهجنا", approach_title:"المعرفة قبل دخول الماء.", approach_text:"نساعد الناس على التعرف على المخاطر وفهم محيطهم واتخاذ قرارات واعية حول المياه.", stat_workshops:"دقيقة للورش", stat_model:"نموذج مجتمعي", stat_free:"مجاني", stat_education:"تعليم تجريبي",
    mission_eyebrow:"مهمتنا", mission_title:"جعل المعرفة بسلامة المياه متاحة للجميع.", mission_text:"تلتزم WaterSafe بجعل التثقيف الموثوق والمتاح حول سلامة المياه متاحاً للمجتمعات في كل مكان. ومن خلال التثقيف المجتمعي والموارد الرقمية والشراكات، نهدف إلى تزويد الناس بالمعرفة والثقة للتعرف على المخاطر المرتبطة بالمياه واتخاذ قرارات أكثر أماناً والوصول إلى فرص لتطوير مهارات أساسية في سلامة المياه.",
    value_safety_title:"السلامة", value_safety_text:"نحوّل المعرفة الأساسية بسلامة المياه إلى إرشادات عملية يمكن للناس فهمها وتذكرها وتطبيقها.", value_access_title:"الإتاحة", value_access_text:"يجب أن يكون التعليم مفهوماً ومتاحاً بغض النظر عن خبرة الشخص السابقة في السباحة أو خلفيته.", value_community_title:"المجتمع", value_community_text:"نعمل إلى جانب المنظمات والمجتمعات بدلاً من بناء نظام منفصل من الصفر.",
    work_eyebrow:"عملنا", work_title:"تعليم مصمم ليصل إلى الآخرين.", work_intro:"نبني موارد قابلة لإعادة الاستخدام يمكن أن تصل إلى الناس حيث يتعلمون ويجتمعون ويتواصلون بالفعل.", work1_title:"ورش مجتمعية", work1_text:"مقدمة مجانية مدتها نحو 30 دقيقة في أساسيات سلامة المياه، مصممة لتستضيفها المنظمات المجتمعية.", work1_li1:"المخاطر الشائعة في المياه", work1_li2:"الإشراف والسلوك الأكثر أماناً", work1_li3:"السترات وأجهزة الطفو الشخصية", work1_li4:"متى وكيف تطلب المساعدة", work1_li5:"الخطوات التالية والموارد المحلية", work2_title:"المكتبة الرقمية", work2_text:"مقاطع فيديو قصيرة وأدلة مرئية وموارد مختصرة تجعل تعلم مفاهيم سلامة المياه ومشاركتها أسهل.", work3_title:"خريطة الموارد", work3_text:"طريقة عملية لربط الناس بدروس السباحة والمرافق المائية وبرامج سلامة المياه الموجودة.", work4_title:"حقيبة الورشة", work4_text:"حزمة قابلة لإعادة الاستخدام للمنظمات الشريكة: عرض تقديمي ودليل للميسّر ومواد للمشاركين وموارد وأدوات تقييم.",
    workshop_eyebrow:"ورشة الـ30 دقيقة", workshop_title:"سهلة الوصول. جادة ومهمة.", workshop_intro:"ورشة WaterSafe هي مقدمة تعليمية لسلامة المياه وليست بديلاً عن التدريب المهني على السباحة أو الإنقاذ أو الإنقاذ المائي أو الإسعافات الأولية.", workshop_request:"اطلب ورشة →", timeline1_title:"افهم المخاطر", timeline1_text:"تعرف على المخاطر في المسابح والبحيرات والأنهار والبيئات الأخرى.", timeline2_title:"اتخذ قرارات أكثر أماناً", timeline2_text:"تعرف على الإشراف والسلوك الآمن وأجهزة الطفو والمفاهيم الخاطئة الشائعة.", timeline3_title:"اعرف ما الذي تفعله بعد ذلك", timeline3_text:"تعرف أين تجد معلومات موثوقة وفرصاً لتطوير مهاراتك.",
    course_eyebrow:"الدورة الرقمية", course_title:"تعلّم بالعمق الذي يناسبك.", course_intro:"مجموعة دروس ذاتية من WaterSafe تساعدك على بناء معرفتك بسلامة المياه في الوقت والمكان المناسبين لك.", course_video_title:"دروس الفيديو قريباً", course_video_text:"ستظهر مقاطع الدورة هنا.", course_lesson1:"فهم مخاطر المياه", course_lesson2:"قرارات أكثر أماناً حول المياه", course_lesson3:"أساسيات الطوارئ",
    resources_eyebrow:"سلامة المياه", resources_title:"تعلّم قبل أن تحتاج إلى المعرفة.", resources_intro:"صُممت مواردنا لتكون واضحة وعملية وسهلة المشاركة.", res1_title:"اعرف البيئة من حولك", res1_text:"قد تتغير المياه بسرعة. تعلّم التعرف على الظروف والمخاطر قبل الدخول.", res2_title:"اعرف حدودك", res2_text:"القدرة على السباحة جزء واحد فقط من سلامة المياه. الاستعداد والوعي مهمان أيضاً.", res3_title:"اعرف أين تتعلم", res3_text:"اعثر على طرق موثوقة للوصول إلى تعليم السباحة وغيرها من برامج التثقيف حول سلامة المياه.", coming_soon:"قريباً →",
    emergency_eyebrow:"أساسيات الطوارئ", emergency_title:"مدّ. ارمِ. لا تدخل.", emergency_intro:"إذا كان شخص ما يواجه مشكلة في الماء، احمِ نفسك أولاً. لا تدخل الماء إلا إذا كنت مدرباً على تنفيذ عملية إنقاذ.", call_911:"اتصل بـ911 في حالات الطوارئ.", em1_title:"القاعدة الذهبية", em1_text:"لا تعرض نفسك للخطر أبداً لإنقاذ شخص آخر. ابقَ على اليابسة واستخدم طريقة إنقاذ آمنة.", em2_title:"مدّ عصاً", em2_text:"من مكان آمن على الشاطئ، مدّ عصاً أو أداة مناسبة نحو الشخص ليتمكن من الإمساك بها.", em3_title:"ارمِ وسيلة طفو", em3_text:"ارمِ وسيلة طفو، مثل حلقة إنقاذ، نحو الشخص. لا تقفز إلى الماء.", em4_title:"لا تدخل أبداً من دون تدريب", em4_text:"قد تكون عمليات الإنقاذ في الماء خطرة. لا تدخل الماء لتنفيذ عملية إنقاذ ما لم تكن مدرباً بشكل مناسب.",
    partners_eyebrow:"للمنظمات", partners_title:"اجلب WaterSafe إلى مجتمعك.", partners_intro:"نتعاون مع المنظمات المجتمعية التي ترغب في تقديم مقدمة متاحة حول سلامة المياه. لا توجد تكلفة على المنظمة أو المشاركين خلال مشروعنا التجريبي.", partner_host:"استضف", partner_host_text:"ورشة مجانية مدتها نحو 30 دقيقة في وقت يناسب برنامجك.", partner_share:"شارك", partner_share_text:"اجعل موارد WaterSafe الرقمية متاحة لمجتمعك.", partner_shape:"ساهم", partner_shape_text:"ساعدنا على فهم احتياجات المجتمع وتحسين البرنامج.", partner_btn:"ناقش شراكة",
    contact_eyebrow:"شارك", contact_title:"لنجعل التثقيف حول سلامة المياه أسهل وصولاً.", contact_intro:"هل ترغب في استضافة ورشة أو مشاركة الموارد أو التطوع أو التعاون مع WaterSafe؟", form_name_label:"الاسم", form_name_placeholder:"اسمك", form_org_label:"المنظمة", form_org_placeholder:"المنظمة (اختياري)", form_email_label:"البريد الإلكتروني", form_email_placeholder:"you@example.com", form_message_label:"كيف يمكننا العمل معاً؟", form_message_placeholder:"أخبرنا قليلاً عن فكرتك...", form_submit:"إرسال الاستفسار", form_note:"هذا النموذج التجريبي جاهز للربط بخدمة البريد الإلكتروني أو النماذج التي تفضلها.", footer_tagline:"افهم الماء. ابقَ آمناً.", footer_text:"تثقيف طلابي حول سلامة المياه."
  },
  es: {
    nav_about:"Sobre nosotros", nav_work:"Nuestro trabajo", nav_resources:"Recursos", nav_course:"Curso digital", nav_emergency:"Conceptos básicos de emergencia", nav_partners:"Para organizaciones", nav_get_involved:"Participa",
    hero_eyebrow:"EDUCACIÓN COMUNITARIA SOBRE SEGURIDAD ACUÁTICA", hero_title1:"Conoce el agua.", hero_title2:"Mantente seguro.", hero_text:"WaterSafe hace que la educación fiable y práctica sobre seguridad acuática sea más accesible para las comunidades mediante talleres, recursos digitales y alianzas comunitarias.", hero_btn1:"Conoce nuestro trabajo", hero_btn2:"Colabora con nosotros",
    approach_label:"NUESTRO ENFOQUE", approach_title:"Conocimiento antes de entrar al agua.", approach_text:"Ayudamos a las personas a reconocer los riesgos, comprender su entorno y tomar decisiones informadas alrededor del agua.", stat_workshops:"min de talleres", stat_model:"modelo comunitario", stat_free:"Gratis", stat_education:"educación piloto",
    mission_eyebrow:"NUESTRA MISIÓN", mission_title:"Hacer accesible para todos el conocimiento sobre seguridad acuática.", mission_text:"WaterSafe se dedica a hacer que la educación fiable y accesible sobre seguridad acuática esté disponible para las comunidades en todas partes. Mediante la educación comunitaria, los recursos digitales y las alianzas, buscamos proporcionar a las personas los conocimientos y la confianza necesarios para reconocer los riesgos relacionados con el agua, tomar decisiones más seguras y encontrar oportunidades para desarrollar habilidades esenciales de seguridad acuática.",
    value_safety_title:"Seguridad", value_safety_text:"Convertimos conocimientos esenciales sobre seguridad acuática en orientación práctica que las personas pueden comprender, recordar y aplicar.", value_access_title:"Accesibilidad", value_access_text:"La educación debe ser comprensible y accesible independientemente de la experiencia previa de natación o del origen de una persona.", value_community_title:"Comunidad", value_community_text:"Trabajamos junto a organizaciones y comunidades en lugar de crear un sistema separado desde cero.",
    work_eyebrow:"NUESTRO TRABAJO", work_title:"Educación diseñada para llegar más lejos.", work_intro:"Creamos recursos reutilizables que pueden llegar a las personas donde ya aprenden, se reúnen y se conectan.", work1_title:"Talleres comunitarios", work1_text:"Una introducción gratuita de aproximadamente 30 minutos a la seguridad acuática esencial, diseñada para ser organizada por organizaciones comunitarias.", work1_li1:"Riesgos acuáticos comunes", work1_li2:"Supervisión y comportamiento más seguro", work1_li3:"Chalecos salvavidas y dispositivos personales de flotación", work1_li4:"Cuándo y cómo pedir ayuda", work1_li5:"Próximos pasos y recursos locales", work2_title:"Biblioteca digital", work2_text:"Videos cortos, guías visuales y recursos concisos que facilitan aprender y compartir conceptos de seguridad acuática.", work3_title:"Mapa de recursos", work3_text:"Una forma práctica de conectar a las personas con clases de natación, instalaciones acuáticas y programas de seguridad acuática existentes.", work4_title:"Kit del taller", work4_text:"Un paquete reutilizable para organizaciones asociadas: presentación, guía para facilitadores, material para participantes, recursos y herramientas de evaluación.",
    workshop_eyebrow:"EL TALLER DE 30 MINUTOS", workshop_title:"Fácil de acceder. Lo bastante serio para marcar la diferencia.", workshop_intro:"El taller de WaterSafe es una introducción educativa a la seguridad acuática y no sustituye la formación profesional en natación, salvamento, rescate o primeros auxilios.", workshop_request:"Solicitar un taller →", timeline1_title:"Comprende los riesgos", timeline1_text:"Reconoce los peligros en piscinas, lagos, ríos y otros entornos.", timeline2_title:"Toma decisiones más seguras", timeline2_text:"Explora la supervisión, el comportamiento seguro, los dispositivos de flotación y las ideas equivocadas comunes.", timeline3_title:"Sabe qué hacer después", timeline3_text:"Aprende dónde encontrar información fiable y oportunidades para desarrollar más habilidades.",
    course_eyebrow:"CURSO DIGITAL", course_title:"Aprende a tu propio ritmo.", course_intro:"Una colección de lecciones de WaterSafe a tu propio ritmo para desarrollar tus conocimientos sobre seguridad acuática cuando y donde aprendas mejor.", course_video_title:"Videos de las lecciones próximamente", course_video_text:"Tus videos del curso aparecerán aquí.", course_lesson1:"Comprender los riesgos del agua", course_lesson2:"Decisiones más seguras alrededor del agua", course_lesson3:"Conceptos básicos de emergencia",
    resources_eyebrow:"SEGURIDAD ACUÁTICA", resources_title:"Aprende antes de necesitarlo.", resources_intro:"Nuestros recursos están diseñados para ser claros, prácticos y fáciles de compartir.", res1_title:"Conoce el entorno", res1_text:"El agua puede cambiar rápidamente. Aprende a identificar las condiciones y los peligros antes de entrar.", res2_title:"Conoce tus límites", res2_text:"La capacidad para nadar es solo una parte de la seguridad acuática. La preparación y la atención también importan.", res3_title:"Sabe dónde aprender", res3_text:"Encuentra vías fiables para acceder a clases de natación y otras formas de educación sobre seguridad acuática.", coming_soon:"Próximamente →",
    emergency_eyebrow:"CONCEPTOS BÁSICOS DE EMERGENCIA", emergency_title:"Alcanza. Lanza. No entres.", emergency_intro:"Si alguien está en problemas en el agua, protégete primero. No entres al agua a menos que tengas formación para realizar un rescate.", call_911:"Llama al 911 en caso de emergencia.", em1_title:"La regla de oro", em1_text:"Nunca te pongas en peligro para rescatar a otra persona. Quédate en tierra y utiliza un método de rescate seguro.", em2_title:"Alcanza con un palo", em2_text:"Desde una posición segura en la orilla, extiende un palo u otro objeto adecuado para que la persona pueda agarrarlo.", em3_title:"Lanza un dispositivo de flotación", em3_text:"Lanza un dispositivo de flotación, como un aro salvavidas, hacia la persona. No te lances al agua.", em4_title:"Nunca entres sin formación", em4_text:"Los rescates acuáticos pueden ser peligrosos. Nunca entres al agua para realizar un rescate si no tienes la formación adecuada.",
    partners_eyebrow:"PARA ORGANIZACIONES", partners_title:"Lleva WaterSafe a tu comunidad.", partners_intro:"Colaboramos con organizaciones comunitarias que quieren ofrecer una introducción accesible a la seguridad acuática. Durante nuestro proyecto piloto, no hay ningún costo para la organización ni para los participantes.", partner_host:"Acoge", partner_host_text:"Un taller gratuito de aproximadamente 30 minutos en un horario que encaje con tu programación.", partner_share:"Comparte", partner_share_text:"Pon los recursos digitales de WaterSafe a disposición de tu comunidad.", partner_shape:"Contribuye", partner_shape_text:"Ayúdanos a comprender las necesidades de la comunidad y mejorar el programa.", partner_btn:"Hablar sobre una colaboración",
    contact_eyebrow:"PARTICIPA", contact_title:"Hagamos que la educación sobre seguridad acuática sea más accesible.", contact_intro:"¿Te interesa organizar un taller, compartir recursos, hacer voluntariado o colaborar con WaterSafe?", form_name_label:"Nombre", form_name_placeholder:"Tu nombre", form_org_label:"Organización", form_org_placeholder:"Organización (opcional)", form_email_label:"Correo electrónico", form_email_placeholder:"you@example.com", form_message_label:"¿Cómo podemos trabajar juntos?", form_message_placeholder:"Cuéntanos un poco sobre tu idea...", form_submit:"Enviar consulta", form_note:"Este formulario de demostración está listo para conectarse con tu servicio de correo o formularios preferido.", footer_tagline:"Conoce el agua. Mantente seguro.", footer_text:"Educación estudiantil sobre seguridad acuática."
  }
};

function applyLanguage(lang){
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if(dict[key] !== undefined) el.textContent = dict[key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if(dict[key] !== undefined) el.placeholder = dict[key];
  });
  localStorage.setItem("watersafe-language", lang);
}

const languageSelect = document.getElementById("language-select");
if(languageSelect){
  languageSelect.addEventListener("change", e => applyLanguage(e.target.value));
  const saved = localStorage.getItem("watersafe-language") || "en";
  languageSelect.value = saved;
  applyLanguage(saved);
}


const menuBtn = document.querySelector('.menu-btn');
const navLinks = document.querySelector('.nav-links');
if(menuBtn){
  menuBtn.addEventListener('click', () => {
    const open = navLinks.classList.toggle('open');
    menuBtn.setAttribute('aria-expanded', open);
  });
}
document.querySelectorAll('.nav-links a').forEach(a => a.addEventListener('click', () => navLinks.classList.remove('open')));
document.getElementById('year').textContent = new Date().getFullYear();

